/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package prabhubank;
import java.sql.*;
import java.awt.CardLayout;
import java.time.LocalDateTime;
import java.util.logging.Level;
import java.util.logging.Logger;
import static prabhubank.PrabhuBank.stmt;

/**
 *
 * @author Annoy
 */
public class OutputChoice extends javax.swing.JFrame {
    PrabhuBank pb;
    /**
     * Creates new form OutputChoice
     * @throws java.lang.ClassNotFoundException
     * @throws java.sql.SQLException
     */
    public OutputChoice() throws ClassNotFoundException, SQLException {
        initComponents();
        pb=new PrabhuBank();
    }
    
    private void switchToPanel(String panelName) {
        CardLayout cardLayout = (CardLayout) MainPanel.getLayout();
        cardLayout.show(MainPanel, panelName);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField1 = new javax.swing.JTextField();
        title = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        MainPanel = new javax.swing.JPanel();
        MenuPanel = new javax.swing.JPanel();
        BalanceInquiry = new javax.swing.JButton();
        changePIN = new javax.swing.JButton();
        withdrawBalance = new javax.swing.JButton();
        miniStatement = new javax.swing.JButton();
        depositBalance = new javax.swing.JButton();
        exit = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        balanceInquiryPanel = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        balanceInquiryTextField = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        balanceInquiryBtn = new javax.swing.JButton();
        miniStatementPanel = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        miniStatementTextArea = new javax.swing.JTextArea();
        miniStatementBtn = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();
        changePinPanel = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        oldPinTextField = new javax.swing.JTextField();
        newPinTextField = new javax.swing.JTextField();
        confirmNewPinTextField = new javax.swing.JTextField();
        changePinBtn = new javax.swing.JButton();
        changePinError = new javax.swing.JLabel();
        withdrawBalancePanel = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        withdrawAmountTextField = new javax.swing.JTextField();
        withdrawBalanceBtn = new javax.swing.JButton();
        withdrawAmountLabel = new javax.swing.JLabel();
        depositBalancePanel = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        depositAmountTextField = new javax.swing.JTextField();
        depositBalanceBtn = new javax.swing.JButton();
        depositAmountError = new javax.swing.JLabel();

        jTextField1.setText("jTextField1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("PrabhuBankATM");

        jLabel1.setFont(new java.awt.Font("Sitka Heading", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(204, 0, 0));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Welcome To PrabhuBank ATM");

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/AtmLogo/prabhu-logo.jpg"))); // NOI18N

        javax.swing.GroupLayout titleLayout = new javax.swing.GroupLayout(title);
        title.setLayout(titleLayout);
        titleLayout.setHorizontalGroup(
            titleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(titleLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        titleLayout.setVerticalGroup(
            titleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, titleLayout.createSequentialGroup()
                .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, 191, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        MainPanel.setLayout(new java.awt.CardLayout());

        BalanceInquiry.setText("Balance Inquiry");
        BalanceInquiry.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BalanceInquiryActionPerformed(evt);
            }
        });

        changePIN.setText("Change PIN");
        changePIN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                changePINActionPerformed(evt);
            }
        });

        withdrawBalance.setText("Withdraw Balance");
        withdrawBalance.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                withdrawBalanceActionPerformed(evt);
            }
        });

        miniStatement.setText("Mini Statement");
        miniStatement.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miniStatementActionPerformed(evt);
            }
        });

        depositBalance.setText("Deposit Balance");
        depositBalance.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                depositBalanceActionPerformed(evt);
            }
        });

        exit.setText("Exit");
        exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitActionPerformed(evt);
            }
        });

        jLabel4.setText("Please select an option below :");

        javax.swing.GroupLayout MenuPanelLayout = new javax.swing.GroupLayout(MenuPanel);
        MenuPanel.setLayout(MenuPanelLayout);
        MenuPanelLayout.setHorizontalGroup(
            MenuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, MenuPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(MenuPanelLayout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(MenuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(changePIN, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(BalanceInquiry, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(withdrawBalance, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 252, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 131, Short.MAX_VALUE)
                .addGroup(MenuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(miniStatement, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(depositBalance, javax.swing.GroupLayout.DEFAULT_SIZE, 259, Short.MAX_VALUE)
                    .addComponent(exit, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(35, 35, 35))
        );
        MenuPanelLayout.setVerticalGroup(
            MenuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MenuPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addGap(31, 31, 31)
                .addGroup(MenuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(BalanceInquiry, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(miniStatement, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addGroup(MenuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(changePIN, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(depositBalance, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addGroup(MenuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(withdrawBalance, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(exit, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(57, Short.MAX_VALUE))
        );

        MainPanel.add(MenuPanel, "cardMenuPanel");

        jLabel3.setText("Remaining Balance : ");

        balanceInquiryTextField.setEditable(false);

        jLabel13.setFont(new java.awt.Font("Sitka Heading", 1, 24)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(0, 153, 51));
        jLabel13.setText("Balance Inquiry");

        balanceInquiryBtn.setBackground(new java.awt.Color(0, 153, 51));
        balanceInquiryBtn.setFont(new java.awt.Font("Sitka Subheading", 0, 20)); // NOI18N
        balanceInquiryBtn.setForeground(new java.awt.Color(255, 255, 255));
        balanceInquiryBtn.setText("Ok");
        balanceInquiryBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                balanceInquiryBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout balanceInquiryPanelLayout = new javax.swing.GroupLayout(balanceInquiryPanel);
        balanceInquiryPanel.setLayout(balanceInquiryPanelLayout);
        balanceInquiryPanelLayout.setHorizontalGroup(
            balanceInquiryPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(balanceInquiryPanelLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(balanceInquiryPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(balanceInquiryPanelLayout.createSequentialGroup()
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(balanceInquiryPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(balanceInquiryBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(balanceInquiryTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 221, Short.MAX_VALUE))
                        .addGap(0, 263, Short.MAX_VALUE)))
                .addContainerGap())
        );
        balanceInquiryPanelLayout.setVerticalGroup(
            balanceInquiryPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(balanceInquiryPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addGroup(balanceInquiryPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(balanceInquiryTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 138, Short.MAX_VALUE)
                .addComponent(balanceInquiryBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15))
        );

        MainPanel.add(balanceInquiryPanel, "cardBalanceInquiry");

        miniStatementTextArea.setEditable(false);
        miniStatementTextArea.setColumns(20);
        miniStatementTextArea.setRows(5);
        jScrollPane1.setViewportView(miniStatementTextArea);

        miniStatementBtn.setBackground(new java.awt.Color(0, 153, 51));
        miniStatementBtn.setFont(new java.awt.Font("Sitka Subheading", 0, 20)); // NOI18N
        miniStatementBtn.setForeground(new java.awt.Color(255, 255, 255));
        miniStatementBtn.setText("Go Back");
        miniStatementBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miniStatementBtnActionPerformed(evt);
            }
        });

        jLabel14.setFont(new java.awt.Font("Sitka Heading", 1, 24)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(0, 153, 51));
        jLabel14.setText("Mini Statement");

        javax.swing.GroupLayout miniStatementPanelLayout = new javax.swing.GroupLayout(miniStatementPanel);
        miniStatementPanel.setLayout(miniStatementPanelLayout);
        miniStatementPanelLayout.setHorizontalGroup(
            miniStatementPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(miniStatementPanelLayout.createSequentialGroup()
                .addGroup(miniStatementPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(miniStatementPanelLayout.createSequentialGroup()
                        .addGroup(miniStatementPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(miniStatementPanelLayout.createSequentialGroup()
                                .addGap(21, 21, 21)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 671, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(miniStatementPanelLayout.createSequentialGroup()
                                .addGap(256, 256, 256)
                                .addComponent(miniStatementBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 16, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, miniStatementPanelLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 692, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        miniStatementPanelLayout.setVerticalGroup(
            miniStatementPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, miniStatementPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(17, 17, 17)
                .addComponent(miniStatementBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        MainPanel.add(miniStatementPanel, "cardMiniStatement");

        jLabel7.setFont(new java.awt.Font("Sitka Heading", 1, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 153, 51));
        jLabel7.setText("Change PIN");

        jLabel8.setFont(new java.awt.Font("Sitka Subheading", 0, 20)); // NOI18N
        jLabel8.setText("Enter Your Previous PIN ");

        jLabel9.setFont(new java.awt.Font("Sitka Subheading", 0, 20)); // NOI18N
        jLabel9.setText("Enter Your New PIN ");

        jLabel10.setFont(new java.awt.Font("Sitka Subheading", 0, 20)); // NOI18N
        jLabel10.setText("Confirm Your New PIN ");

        changePinBtn.setBackground(new java.awt.Color(0, 153, 51));
        changePinBtn.setFont(new java.awt.Font("Sitka Subheading", 0, 20)); // NOI18N
        changePinBtn.setForeground(new java.awt.Color(255, 255, 255));
        changePinBtn.setText("Confirm");
        changePinBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                changePinBtnActionPerformed(evt);
            }
        });

        changePinError.setFont(new java.awt.Font("Sitka Small", 0, 18)); // NOI18N
        changePinError.setForeground(new java.awt.Color(255, 0, 0));

        javax.swing.GroupLayout changePinPanelLayout = new javax.swing.GroupLayout(changePinPanel);
        changePinPanel.setLayout(changePinPanelLayout);
        changePinPanelLayout.setHorizontalGroup(
            changePinPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(changePinPanelLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(changePinPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(changePinPanelLayout.createSequentialGroup()
                        .addComponent(changePinError, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(changePinPanelLayout.createSequentialGroup()
                        .addGroup(changePinPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(changePinPanelLayout.createSequentialGroup()
                                .addGroup(changePinPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel8)
                                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 86, Short.MAX_VALUE))
                            .addGroup(changePinPanelLayout.createSequentialGroup()
                                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(42, 42, 42)
                                .addGroup(changePinPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(newPinTextField)
                                    .addComponent(confirmNewPinTextField)
                                    .addComponent(oldPinTextField)
                                    .addComponent(changePinBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                        .addGap(212, 212, 212))))
        );
        changePinPanelLayout.setVerticalGroup(
            changePinPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(changePinPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(changePinPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(oldPinTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(changePinPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(newPinTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(changePinPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(confirmNewPinTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(changePinError)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 66, Short.MAX_VALUE)
                .addComponent(changePinBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        MainPanel.add(changePinPanel, "cardChangePin");

        jLabel11.setFont(new java.awt.Font("Sitka Heading", 1, 24)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(0, 153, 51));
        jLabel11.setText("Withdraw Balance");

        jLabel12.setFont(new java.awt.Font("Sitka Subheading", 0, 20)); // NOI18N
        jLabel12.setText("Withdraw Balance        : ");

        withdrawBalanceBtn.setBackground(new java.awt.Color(0, 153, 51));
        withdrawBalanceBtn.setFont(new java.awt.Font("Sitka Subheading", 0, 20)); // NOI18N
        withdrawBalanceBtn.setForeground(new java.awt.Color(255, 255, 255));
        withdrawBalanceBtn.setText("Confirm");
        withdrawBalanceBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                withdrawBalanceBtnActionPerformed(evt);
            }
        });

        withdrawAmountLabel.setFont(new java.awt.Font("Sitka Small", 0, 18)); // NOI18N
        withdrawAmountLabel.setForeground(new java.awt.Color(204, 0, 0));

        javax.swing.GroupLayout withdrawBalancePanelLayout = new javax.swing.GroupLayout(withdrawBalancePanel);
        withdrawBalancePanel.setLayout(withdrawBalancePanelLayout);
        withdrawBalancePanelLayout.setHorizontalGroup(
            withdrawBalancePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(withdrawBalancePanelLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(withdrawBalancePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(withdrawBalancePanelLayout.createSequentialGroup()
                        .addGroup(withdrawBalancePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(withdrawBalancePanelLayout.createSequentialGroup()
                                .addComponent(jLabel12)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(withdrawBalancePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(withdrawBalanceBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(withdrawAmountTextField))))
                        .addGap(0, 286, Short.MAX_VALUE))
                    .addComponent(withdrawAmountLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        withdrawBalancePanelLayout.setVerticalGroup(
            withdrawBalancePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(withdrawBalancePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(withdrawBalancePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(withdrawAmountTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(withdrawAmountLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 145, Short.MAX_VALUE)
                .addComponent(withdrawBalanceBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15))
        );

        MainPanel.add(withdrawBalancePanel, "cardWithdrawBalance");

        jLabel15.setFont(new java.awt.Font("Sitka Heading", 1, 24)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(0, 153, 51));
        jLabel15.setText("Deposit Balance");

        jLabel16.setFont(new java.awt.Font("Sitka Subheading", 0, 20)); // NOI18N
        jLabel16.setText("Deposit Balance        : ");

        depositBalanceBtn.setBackground(new java.awt.Color(0, 153, 51));
        depositBalanceBtn.setFont(new java.awt.Font("Sitka Subheading", 0, 20)); // NOI18N
        depositBalanceBtn.setForeground(new java.awt.Color(255, 255, 255));
        depositBalanceBtn.setText("Confirm");
        depositBalanceBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                depositBalanceBtnActionPerformed(evt);
            }
        });

        depositAmountError.setFont(new java.awt.Font("Sitka Small", 0, 18)); // NOI18N
        depositAmountError.setForeground(new java.awt.Color(255, 0, 0));

        javax.swing.GroupLayout depositBalancePanelLayout = new javax.swing.GroupLayout(depositBalancePanel);
        depositBalancePanel.setLayout(depositBalancePanelLayout);
        depositBalancePanelLayout.setHorizontalGroup(
            depositBalancePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(depositBalancePanelLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(depositBalancePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel15, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(depositBalancePanelLayout.createSequentialGroup()
                        .addComponent(jLabel16)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(depositBalancePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(depositBalanceBtn, javax.swing.GroupLayout.DEFAULT_SIZE, 176, Short.MAX_VALUE)
                            .addComponent(depositAmountTextField))
                        .addGap(0, 306, Short.MAX_VALUE))
                    .addComponent(depositAmountError, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        depositBalancePanelLayout.setVerticalGroup(
            depositBalancePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(depositBalancePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(depositBalancePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(depositAmountTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(depositAmountError)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 154, Short.MAX_VALUE)
                .addComponent(depositBalanceBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        MainPanel.add(depositBalancePanel, "cardDepositBalance");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(MainPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(title, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(title, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(MainPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BalanceInquiryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BalanceInquiryActionPerformed
        switchToPanel("cardBalanceInquiry");
        String sql = "SELECT * FROM `customer_statement`";
        ResultSet rs;
        try {
            rs = stmt.executeQuery(sql);
            while (rs.next()) {
                balanceInquiryTextField.setText(Double.toString(rs.getDouble("balance")));
                
            }
        } catch (SQLException ex) {
            Logger.getLogger(OutputChoice.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_BalanceInquiryActionPerformed

    private void exitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitActionPerformed
        System.exit(0);
    }//GEN-LAST:event_exitActionPerformed

    private void miniStatementActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miniStatementActionPerformed
        switchToPanel("cardMiniStatement");
        String sql = "SELECT * FROM `customer_statement`";
        ResultSet rs;
        try {
            rs = stmt.executeQuery(sql);
            while (rs.next()) {
                miniStatementTextArea.append(
                        "**Transaction " + rs.getString("id")
                        + "**\n Account Holder Name : " + rs.getString("name")
                        + "\n Transaction Time : " + rs.getTimestamp("transaction_time")
                        + "\n" + rs.getString("description") + " Amount : " + rs.getDouble("amount")
                        + "\nTotal Balance : " + rs.getDouble("balance")+"\n");
            }
        } catch (SQLException ex) {
            Logger.getLogger(OutputChoice.class.getName()).log(Level.SEVERE, null, ex);
        }

        
    }//GEN-LAST:event_miniStatementActionPerformed

    private void changePINActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_changePINActionPerformed
        switchToPanel("cardChangePin");
    }//GEN-LAST:event_changePINActionPerformed

    private void depositBalanceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_depositBalanceActionPerformed
        switchToPanel("cardDepositBalance");
    }//GEN-LAST:event_depositBalanceActionPerformed

    private void withdrawBalanceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_withdrawBalanceActionPerformed
        switchToPanel("cardWithdrawBalance");
    }//GEN-LAST:event_withdrawBalanceActionPerformed

    private void balanceInquiryBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_balanceInquiryBtnActionPerformed
        switchToPanel("cardMenuPanel");
    }//GEN-LAST:event_balanceInquiryBtnActionPerformed

    private void miniStatementBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miniStatementBtnActionPerformed
        switchToPanel("cardMenuPanel");
    }//GEN-LAST:event_miniStatementBtnActionPerformed

    private void changePinBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_changePinBtnActionPerformed
        int op = Integer.parseInt(oldPinTextField.getText());

        if (op == pb.PIN) {
            int np = Integer.parseInt(newPinTextField.getText());
            
            int npc = Integer.parseInt(confirmNewPinTextField.getText());
            if (np == npc) {
                pb.PIN = np;
                String sql = "UPDATE `customer` set pin='" + pb.PIN + "' WHERE id= 1";
                try {
                    stmt.executeUpdate(sql);
                } catch (SQLException ex) {
                    Logger.getLogger(OutputChoice.class.getName()).log(Level.SEVERE, null, ex);
                }
                System.out.println("PIN changed Successfully!");
                switchToPanel("cardMenuPanel");
            } else {
                changePinError.setText("Wrong New PIN Confirmation!");
                switchToPanel("cardChangePin");
            }
        } else {
            changePinError.setText("Wrong Old PIN!");
            switchToPanel("cardChangePin");
        }
    }//GEN-LAST:event_changePinBtnActionPerformed

    private void withdrawBalanceBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_withdrawBalanceBtnActionPerformed
        double withdrawAmount;
        withdrawAmount= Double.parseDouble(withdrawAmountTextField.getText());

        if (withdrawAmount % 500 == 0) {
            if (withdrawAmount < 500) {
                withdrawAmountLabel.setText("Required Minimum Balance Rs 500.");
                switchToPanel("cardWithdrawBalance");
            } else if (withdrawAmount > pb.balance) {
                withdrawAmountLabel.setText("Not Sufficient Balance in your account.");
                switchToPanel("cardWithdrawBalance");
            } else if (pb.balance <= 500) {
                withdrawAmountLabel.setText("You atleast minimum balance of Rs 500 in your Account");
                switchToPanel("cardWithdrawBalance");
            } else if (withdrawAmount == pb.balance) {
                withdrawAmountLabel.setText("You atleast minimum balance of Rs 500 in your Account");
                switchToPanel("cardWithdrawBalance");
            } else {
                pb.balance = pb.balance - withdrawAmount;
                LocalDateTime currentDateTime = LocalDateTime.now();
                String description = "Withdraw";
                String sql = "INSERT INTO `customer_statement` (`name`,`transaction_time` ,`description`, `amount`, `balance`) values ('" + pb.customerName + "', '" + currentDateTime + "', '" + description + "', '" + withdrawAmount + "', '" + pb.balance + "')";
                try {
                    stmt.executeUpdate(sql);
                } catch (SQLException ex) {
                    Logger.getLogger(OutputChoice.class.getName()).log(Level.SEVERE, null, ex);
                }
                switchToPanel("cardMenuPanel");
                //System.out.println("You have Successfully Withdraw Amount : " + withdrawAmount);

            }
        } else {
            withdrawAmountLabel.setText("Only Rs.500 and Rs.1000 Notes are available!");
            switchToPanel("cardWithdrawBalance");
        }
        
    }//GEN-LAST:event_withdrawBalanceBtnActionPerformed

    private void depositBalanceBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_depositBalanceBtnActionPerformed
        double depositAmount;
        depositAmount = Double.parseDouble(depositAmountTextField.getText());
        if (depositAmount % 500 == 0) {
            if (depositAmount < 500) {
                depositAmountError.setText("Required Minimum Balance Rs 500.");
                switchToPanel("cardDepositBalance");
            } else {
                pb.balance = pb.balance + depositAmount;
                String sql1 = "UPDATE `customer` set balance='"+pb.balance+"' WHERE id= 1";
                try { 
                    stmt.executeUpdate(sql1);
                } catch (SQLException ex) {
                    Logger.getLogger(OutputChoice.class.getName()).log(Level.SEVERE, null, ex);
                }
                LocalDateTime currentDateTime = LocalDateTime.now();
                String description = "Deposit";
                String sql = "INSERT INTO `customer_statement` (`name`, `transaction_time`, `description`, `amount`, `balance`) values ('" + pb.customerName + "', '" + currentDateTime + "', '" + description + "', '" + depositAmount + "', '" + pb.balance + "')";
                try {
                    stmt.executeUpdate(sql);
                } catch (SQLException ex) {
                    Logger.getLogger(OutputChoice.class.getName()).log(Level.SEVERE, null, ex);
                }

                switchToPanel("cardMenuPanel");
                //System.out.println("You have Successfully Deposit Amount : " + depositAmount);

            }
        } else {
            depositAmountError.setText("Only Rs.500 and Rs.1000 Notes are available!");
            switchToPanel("cardDepositBalance");
        }
        

    }//GEN-LAST:event_depositBalanceBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BalanceInquiry;
    private javax.swing.JPanel MainPanel;
    private javax.swing.JPanel MenuPanel;
    private javax.swing.JButton balanceInquiryBtn;
    private javax.swing.JPanel balanceInquiryPanel;
    private javax.swing.JTextField balanceInquiryTextField;
    private javax.swing.JButton changePIN;
    private javax.swing.JButton changePinBtn;
    private javax.swing.JLabel changePinError;
    private javax.swing.JPanel changePinPanel;
    private javax.swing.JTextField confirmNewPinTextField;
    private javax.swing.JLabel depositAmountError;
    private javax.swing.JTextField depositAmountTextField;
    private javax.swing.JButton depositBalance;
    private javax.swing.JButton depositBalanceBtn;
    private javax.swing.JPanel depositBalancePanel;
    private javax.swing.JButton exit;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JButton miniStatement;
    private javax.swing.JButton miniStatementBtn;
    private javax.swing.JPanel miniStatementPanel;
    private javax.swing.JTextArea miniStatementTextArea;
    private javax.swing.JTextField newPinTextField;
    private javax.swing.JTextField oldPinTextField;
    private javax.swing.JPanel title;
    private javax.swing.JLabel withdrawAmountLabel;
    private javax.swing.JTextField withdrawAmountTextField;
    private javax.swing.JButton withdrawBalance;
    private javax.swing.JButton withdrawBalanceBtn;
    private javax.swing.JPanel withdrawBalancePanel;
    // End of variables declaration//GEN-END:variables
}
