/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package prabhubank;
import java.sql.*;
import java.awt.CardLayout;
import java.util.logging.Level;
import java.util.logging.Logger;
import static prabhubank.PrabhuBank.stmt;

/**
 *
 * @author Annoy
 */
public class UserValidation extends javax.swing.JFrame {
    PrabhuBank pb;
    /**
     * Creates new form OutputChoice
     * @throws java.lang.ClassNotFoundException
     * @throws java.sql.SQLException
     */
    public UserValidation() throws ClassNotFoundException, SQLException {
        initComponents();
        pb=new PrabhuBank();
    }
    
    private void switchToPanel(String panelName) {
        CardLayout cardLayout = (CardLayout) MainPanel.getLayout();
        cardLayout.show(MainPanel, panelName);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField1 = new javax.swing.JTextField();
        title = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        MainPanel = new javax.swing.JPanel();
        cardNumberValidationPanel = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        cardNumberTextField = new javax.swing.JTextField();
        cardNumberBtn = new javax.swing.JButton();
        cardValidationError = new javax.swing.JLabel();
        PinValidationPanel = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        pinNumberTextField = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        PinValidationError = new javax.swing.JLabel();
        cardNumberValidationPanel1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        cardNumberTextField1 = new javax.swing.JTextField();
        cardNumberBtn1 = new javax.swing.JButton();
        cardValidationError1 = new javax.swing.JLabel();
        cardNumberValidationPanel2 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        cardNumberTextField2 = new javax.swing.JTextField();
        cardNumberBtn2 = new javax.swing.JButton();
        cardValidationError2 = new javax.swing.JLabel();
        cardNumberValidationPanel3 = new javax.swing.JPanel();
        cardNumberBtn3 = new javax.swing.JButton();
        cardValidationError3 = new javax.swing.JLabel();

        jTextField1.setText("jTextField1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("PrabhuBankATM");

        jLabel1.setFont(new java.awt.Font("Sitka Heading", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(204, 0, 0));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Welcome To PrabhuBank ATM");

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/AtmLogo/prabhu-logo.jpg"))); // NOI18N

        javax.swing.GroupLayout titleLayout = new javax.swing.GroupLayout(title);
        title.setLayout(titleLayout);
        titleLayout.setHorizontalGroup(
            titleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(titleLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        titleLayout.setVerticalGroup(
            titleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, titleLayout.createSequentialGroup()
                .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, 191, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        MainPanel.setLayout(new java.awt.CardLayout());

        jLabel2.setFont(new java.awt.Font("Sitka Subheading", 0, 24)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Please Enter Your CardNumber");

        cardNumberBtn.setBackground(new java.awt.Color(204, 0, 0));
        cardNumberBtn.setFont(new java.awt.Font("Sitka Heading", 0, 24)); // NOI18N
        cardNumberBtn.setForeground(new java.awt.Color(255, 255, 255));
        cardNumberBtn.setText("Submit");
        cardNumberBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cardNumberBtnActionPerformed(evt);
            }
        });

        cardValidationError.setForeground(new java.awt.Color(204, 0, 51));

        javax.swing.GroupLayout cardNumberValidationPanelLayout = new javax.swing.GroupLayout(cardNumberValidationPanel);
        cardNumberValidationPanel.setLayout(cardNumberValidationPanelLayout);
        cardNumberValidationPanelLayout.setHorizontalGroup(
            cardNumberValidationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cardNumberValidationPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(cardNumberValidationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(cardNumberValidationPanelLayout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, cardNumberValidationPanelLayout.createSequentialGroup()
                        .addGap(0, 271, Short.MAX_VALUE)
                        .addComponent(cardNumberBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(272, 272, 272))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, cardNumberValidationPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(cardNumberValidationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(cardNumberTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 340, Short.MAX_VALUE)
                    .addComponent(cardValidationError, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(182, 182, 182))
        );
        cardNumberValidationPanelLayout.setVerticalGroup(
            cardNumberValidationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cardNumberValidationPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cardNumberTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cardValidationError)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 82, Short.MAX_VALUE)
                .addComponent(cardNumberBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(49, 49, 49))
        );

        MainPanel.add(cardNumberValidationPanel, "card2");

        jLabel3.setFont(new java.awt.Font("Sitka Subheading", 0, 24)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Please Enter Your PIN Number");

        jButton2.setBackground(new java.awt.Color(204, 0, 0));
        jButton2.setFont(new java.awt.Font("Sitka Heading", 0, 24)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("Submit");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        PinValidationError.setFont(new java.awt.Font("Sitka Heading", 0, 18)); // NOI18N
        PinValidationError.setForeground(new java.awt.Color(204, 0, 0));

        javax.swing.GroupLayout PinValidationPanelLayout = new javax.swing.GroupLayout(PinValidationPanel);
        PinValidationPanel.setLayout(PinValidationPanelLayout);
        PinValidationPanelLayout.setHorizontalGroup(
            PinValidationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PinValidationPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PinValidationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PinValidationPanelLayout.createSequentialGroup()
                        .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PinValidationPanelLayout.createSequentialGroup()
                        .addGap(0, 271, Short.MAX_VALUE)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(272, 272, 272))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PinValidationPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(PinValidationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(pinNumberTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 340, Short.MAX_VALUE)
                    .addComponent(PinValidationError, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(182, 182, 182))
        );
        PinValidationPanelLayout.setVerticalGroup(
            PinValidationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PinValidationPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pinNumberTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(PinValidationError)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 82, Short.MAX_VALUE)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(49, 49, 49))
        );

        MainPanel.add(PinValidationPanel, "cardPinValidation");

        jLabel4.setFont(new java.awt.Font("Sitka Subheading", 0, 24)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Please Enter Your CardNumber");

        cardNumberBtn1.setBackground(new java.awt.Color(204, 0, 0));
        cardNumberBtn1.setFont(new java.awt.Font("Sitka Heading", 0, 24)); // NOI18N
        cardNumberBtn1.setForeground(new java.awt.Color(255, 255, 255));
        cardNumberBtn1.setText("Submit");
        cardNumberBtn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cardNumberBtn1ActionPerformed(evt);
            }
        });

        cardValidationError1.setForeground(new java.awt.Color(204, 0, 51));

        javax.swing.GroupLayout cardNumberValidationPanel1Layout = new javax.swing.GroupLayout(cardNumberValidationPanel1);
        cardNumberValidationPanel1.setLayout(cardNumberValidationPanel1Layout);
        cardNumberValidationPanel1Layout.setHorizontalGroup(
            cardNumberValidationPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cardNumberValidationPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(cardNumberValidationPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(cardNumberValidationPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, cardNumberValidationPanel1Layout.createSequentialGroup()
                        .addGap(0, 271, Short.MAX_VALUE)
                        .addComponent(cardNumberBtn1, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(272, 272, 272))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, cardNumberValidationPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(cardNumberValidationPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(cardNumberTextField1, javax.swing.GroupLayout.DEFAULT_SIZE, 340, Short.MAX_VALUE)
                    .addComponent(cardValidationError1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(182, 182, 182))
        );
        cardNumberValidationPanel1Layout.setVerticalGroup(
            cardNumberValidationPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cardNumberValidationPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cardNumberTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cardValidationError1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 82, Short.MAX_VALUE)
                .addComponent(cardNumberBtn1, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(49, 49, 49))
        );

        MainPanel.add(cardNumberValidationPanel1, "cardNumberBtn1Card");

        jLabel5.setFont(new java.awt.Font("Sitka Subheading", 0, 24)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Please Enter Your CardNumber");

        cardNumberBtn2.setBackground(new java.awt.Color(204, 0, 0));
        cardNumberBtn2.setFont(new java.awt.Font("Sitka Heading", 0, 24)); // NOI18N
        cardNumberBtn2.setForeground(new java.awt.Color(255, 255, 255));
        cardNumberBtn2.setText("Submit");
        cardNumberBtn2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cardNumberBtn2ActionPerformed(evt);
            }
        });

        cardValidationError2.setForeground(new java.awt.Color(204, 0, 51));

        javax.swing.GroupLayout cardNumberValidationPanel2Layout = new javax.swing.GroupLayout(cardNumberValidationPanel2);
        cardNumberValidationPanel2.setLayout(cardNumberValidationPanel2Layout);
        cardNumberValidationPanel2Layout.setHorizontalGroup(
            cardNumberValidationPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cardNumberValidationPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(cardNumberValidationPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(cardNumberValidationPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, cardNumberValidationPanel2Layout.createSequentialGroup()
                        .addGap(0, 271, Short.MAX_VALUE)
                        .addComponent(cardNumberBtn2, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(272, 272, 272))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, cardNumberValidationPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(cardNumberValidationPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(cardNumberTextField2, javax.swing.GroupLayout.DEFAULT_SIZE, 340, Short.MAX_VALUE)
                    .addComponent(cardValidationError2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(182, 182, 182))
        );
        cardNumberValidationPanel2Layout.setVerticalGroup(
            cardNumberValidationPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cardNumberValidationPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cardNumberTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cardValidationError2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 82, Short.MAX_VALUE)
                .addComponent(cardNumberBtn2, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(49, 49, 49))
        );

        MainPanel.add(cardNumberValidationPanel2, "cardNumberBtn2Card");

        cardNumberBtn3.setBackground(new java.awt.Color(204, 0, 0));
        cardNumberBtn3.setFont(new java.awt.Font("Sitka Heading", 0, 24)); // NOI18N
        cardNumberBtn3.setForeground(new java.awt.Color(255, 255, 255));
        cardNumberBtn3.setText("Exit");
        cardNumberBtn3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cardNumberBtn3ActionPerformed(evt);
            }
        });

        cardValidationError3.setForeground(new java.awt.Color(204, 0, 51));

        javax.swing.GroupLayout cardNumberValidationPanel3Layout = new javax.swing.GroupLayout(cardNumberValidationPanel3);
        cardNumberValidationPanel3.setLayout(cardNumberValidationPanel3Layout);
        cardNumberValidationPanel3Layout.setHorizontalGroup(
            cardNumberValidationPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cardNumberValidationPanel3Layout.createSequentialGroup()
                .addContainerGap(277, Short.MAX_VALUE)
                .addComponent(cardNumberBtn3, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(272, 272, 272))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, cardNumberValidationPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(cardValidationError3, javax.swing.GroupLayout.PREFERRED_SIZE, 340, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(182, 182, 182))
        );
        cardNumberValidationPanel3Layout.setVerticalGroup(
            cardNumberValidationPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cardNumberValidationPanel3Layout.createSequentialGroup()
                .addGap(105, 105, 105)
                .addComponent(cardValidationError3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 82, Short.MAX_VALUE)
                .addComponent(cardNumberBtn3, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(49, 49, 49))
        );

        MainPanel.add(cardNumberValidationPanel3, "cardNumberBtn3Card");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(MainPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(title, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(title, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(MainPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cardNumberBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cardNumberBtnActionPerformed
        if(pb.cardNumber.equals(cardNumberTextField.getText())){
            switchToPanel("cardPinValidation");
        }else{
            switchToPanel("cardNumberBtn1Card");
            cardValidationError1.setText("Please Enter a Valid Card Number! you have 2 attempt left!");
        }
    }//GEN-LAST:event_cardNumberBtnActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        if(String.valueOf(pb.PIN).equals(pinNumberTextField.getText())){
            OutputChoice oc;
            try {
                oc = new OutputChoice();
                oc.setVisible(true);
            } catch (ClassNotFoundException | SQLException ex) {
                Logger.getLogger(UserValidation.class.getName()).log(Level.SEVERE, null, ex);
            }
            
        }else{
            cardValidationError.setText("Please Enter a Valid PIN Number!");
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void cardNumberBtn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cardNumberBtn1ActionPerformed
        if(pb.cardNumber.equals(cardNumberTextField.getText())){
            switchToPanel("cardPinValidation");
        }else{
            switchToPanel("cardNumberBtn2Card");
            cardValidationError2.setText("Please Enter a Valid Card Number! you have 1 attempt left!");
        }
    }//GEN-LAST:event_cardNumberBtn1ActionPerformed

    private void cardNumberBtn2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cardNumberBtn2ActionPerformed
        if(pb.cardNumber.equals(cardNumberTextField.getText())){
            switchToPanel("cardPinValidation");
        }else{
            switchToPanel("cardNumberBtn3Card");
            cardValidationError3.setText("OOPs! Your account has been blocked. Please contact our Bank.Thank You!");
        }
    }//GEN-LAST:event_cardNumberBtn2ActionPerformed

    private void cardNumberBtn3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cardNumberBtn3ActionPerformed
        String sql = "UPDATE customer SET status = false";
        try {
            stmt.executeUpdate(sql);
        } catch (SQLException ex) {
            Logger.getLogger(UserValidation.class.getName()).log(Level.SEVERE, null, ex);
        }
        System.exit(0);
    }//GEN-LAST:event_cardNumberBtn3ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel MainPanel;
    private javax.swing.JLabel PinValidationError;
    private javax.swing.JPanel PinValidationPanel;
    private javax.swing.JButton cardNumberBtn;
    private javax.swing.JButton cardNumberBtn1;
    private javax.swing.JButton cardNumberBtn2;
    private javax.swing.JButton cardNumberBtn3;
    private javax.swing.JTextField cardNumberTextField;
    private javax.swing.JTextField cardNumberTextField1;
    private javax.swing.JTextField cardNumberTextField2;
    private javax.swing.JPanel cardNumberValidationPanel;
    private javax.swing.JPanel cardNumberValidationPanel1;
    private javax.swing.JPanel cardNumberValidationPanel2;
    private javax.swing.JPanel cardNumberValidationPanel3;
    private javax.swing.JLabel cardValidationError;
    private javax.swing.JLabel cardValidationError1;
    private javax.swing.JLabel cardValidationError2;
    private javax.swing.JLabel cardValidationError3;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField pinNumberTextField;
    private javax.swing.JPanel title;
    // End of variables declaration//GEN-END:variables
}
